### PR TITLE
Crameri-Michelson colour maps

### PR DESCRIPTION
**Pull request by DanielMichelson**
One colour map for depolarization ratio and another for RHOHV.

### CODE REVIEW

**Comment by zssherman** [comment]
Thanks @DanielMichelson for the PR! @mgrover1 I'm going to work on the PR and get it ready with the init etc

**Comment by zssherman** [comment]
@DanielMichelson @mgrover1 With trying to shorten the naming, would MCRoma and MCOleron work?(MichelsonCrameri, this way instead of CM to not be confused with ColorMap) Or do we prefer CrameriMichelsonOleron and CrameriMichelsonRoma? Or does anyone have other suggestions?

**Comment by DanielMichelson** [comment]
Whatever works best for the project. The use of each colour map is specific to a given variable (moment), DR and RHOHV; neither colour map is very useful with other variables, so that's why they are each mentioned in the current file names. But the other colour maps that are in the project are more general, and can be applied to more than a single variable. Maybe you would prefer to leave the variable name out of the colour map's name.

**Comment by mgrover1** [comment]
> Whatever works best for the project. The use of each colour map is specific to a given variable (moment), DR and RHOHV; neither colour map is very useful with other variables, so that's why they are each mentioned in the current file names. But the other colour maps that are in the project are more general, and can be applied to more than a single variable. Maybe you would prefer to leave the variable name out of the colour map's name.

I think sticking with the original proposal here... using
`CM_depol`
`CM_rhohv`

This strikes a good balance between being  short enough to easily type out, while also being descriptive for colormaps for those moments. Any thoughts here @DanielMichelson ?

**Comment by zssherman** [comment]
@DanielMichelson Going to merge this in and work on the changes in another PR, thanks again for submitting this!

**Pull request merged**
